app = "stagecrew-web"
primary_region = "nrt"

[build]

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

  [[services.http_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "GET"
    path = "/"
    protocol = "http"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
